name: CI

on:
  pull_request
  
jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install
      - name: Run linter over all packages
        run: bun --filter '*' lint
      - name: Run tests from all packages
        run: bun --filter '*' test